export const referenceBrauliWheelPositions = {
  person: {
    isoLocal:        '1986-02-12T18:10',
    tzOffsetMinutes: -120,
    placeLabel:      'São José dos Campos, SP — Brasil',
  },
  placements: [
    { layer: 'personality', planet: 'Sun', gate: 49, sign: '♒' },
    { layer: 'design', planet: 'Sun', gate: 14, sign: '♐' },
    { layer: 'personality', planet: 'Earth', gate: 4, sign: '♌' },
    { layer: 'design', planet: 'Earth', gate: 8, sign: '♉' },
    { layer: 'personality', planet: 'NorthNode', gate: 27, sign: '♉' },
    { layer: 'design', planet: 'NorthNode', gate: 24, sign: '♉' },
    { layer: 'personality', planet: 'SouthNode', gate: 28, sign: '♏' },
    { layer: 'design', planet: 'SouthNode', gate: 44, sign: '♏' },
    { layer: 'personality', planet: 'Moon', gate: 21, sign: '♈' },
    { layer: 'design', planet: 'Moon', gate: 19, sign: '♒' },
    { layer: 'personality', planet: 'Mercury', gate: 55, sign: '♒' },
    { layer: 'design', planet: 'Mercury', gate: 5, sign: '♐' },
    { layer: 'personality', planet: 'Venus', gate: 30, sign: '♒' },
    { layer: 'design', planet: 'Venus', gate: 44, sign: '♏' },
    { layer: 'personality', planet: 'Mars', gate: 9, sign: '♐' },
    { layer: 'design', planet: 'Mars', gate: 48, sign: '♎' },
    { layer: 'personality', planet: 'Jupiter', gate: 30, sign: '♒' },
    { layer: 'design', planet: 'Jupiter', gate: 19, sign: '♒' },
    { layer: 'personality', planet: 'Saturn', gate: 9, sign: '♐' },
    { layer: 'design', planet: 'Saturn', gate: 34, sign: '♏' },
    { layer: 'personality', planet: 'Uranus', gate: 26, sign: '♐' },
    { layer: 'design', planet: 'Uranus', gate: 5, sign: '♐' },
    { layer: 'personality', planet: 'Neptune', gate: 58, sign: '♑' },
    { layer: 'design', planet: 'Neptune', gate: 10, sign: '♐' },
    { layer: 'personality', planet: 'Pluto', gate: 28, sign: '♎' },
    { layer: 'design', planet: 'Pluto', gate: 28, sign: '♎' },
  ],
}
